local CONFIG = {
    KingMode = false,
    WalkSpeed = 50,
    JumpPower = 150,
    SpeedBoost = false,
    SuperJump = false,
    FPSBoost = true,
    DisableParticles = false,
    ShowFPS = false,
    Noclip = false,
    BoxESP = false,
    PlayerInfo = false,
    TeamFilter = false,
    Invisibility = false,
    ESPColor = Color3.fromRGB(0, 255, 0),
    BoxRainbow = false,
    TeammateName = Color3.fromRGB(50, 220, 100),
    EnemyName = Color3.fromRGB(220, 50, 50),
    NPCBoxESP = false,
    NPCMonster = false,
    NPCItem = false,
    NPCMonsterColor = Color3.fromRGB(220, 50, 50),
    NPCItemColor = Color3.fromRGB(255, 165, 0),
    Aimbot = false,
    AimbotTarget = "head",
    AimbotPlayers = true,
    AimbotMonsters = false,
    Scare = false,
    Fling = false,
    WalkFling = false,
    AntiFling = false,
}

return CONFIG
